export const COLORS = {
    //darkFontColor: (Appearance.getColorScheme() === "dark") ? '#ffffff' : '#000000',
    theme : '#FFFFFF',
    button: '#1F9CEF',
    introText: '#0F141A',
    loginTextInput : '#fff',
    loginText: '#11203D',
    registerTextInput : '#222B2E',
    textInputBorder: '#fff',
    label: '#222B2E',
    white: '#FFFFFF',
    lightgray: '#eee',
    gray: '#A9A9A9',
    cream : '#FEF5E7',
    black: '#000',
    green: '#229954',
    lightgreen: '#36D67F',
    yellow:'yellow',
    orange:'orange',
    red : 'red',
    blue: '#1F9CEF',
    textInput: '#fff',
    logoColor: '#FFA500',
    registratioButton: '#FD9C4A',
    themeColor :'#FF641E',
    BadlandsOrange: "#FE6518",
    itemSeperator : "#CED0CE",
    headerBackground: '#444',
    textListColor: '#444',
    textListColorBold: '#212529',
    headerMenuInactive: '#67CDFF',
    saveButtonColor : '#35D67F',
    cancelButtonColor : '#F13849',
    editButtonColor : '#FE8640',
    textColorLightGrey : '#949494'
}